language: php

php:
    - "hhvm"
    - "hhvm-nightly"

before_script:
    - composer install --prefer-source
    - bin/scanroutes Test/Fixtures/ exclude Test/Fixtures/Ignore/

script:
    - vendor/bin/hackunit Test/
